# =============================================================================
# config/config.py
# Generated : 2026-05-21T09:43:17.576254+00:00
# Auto-generated by build_config.py — do not edit by hand.
# To update test definitions re-run:  python build_config.py
# To update infrastructure values edit the constants in build_config.py.
# =============================================================================

TABLE_CONFIG = {
    'database': 'sample_table',
    'table': 'input_table',
    'table_type': 'ICEBERG',
    's3_location': 's3://input-table/iceberg/',
}

S3_OUTPUT_CONFIG = {
    'bucket': 'outputcsv-bucket-demo',
    'prefix': 'results_folder/',
    'athena_query_results': 's3://outputcsv-bucket-demo/athena-temp/',
}

SETTINGS = {
    'fail_fast': False,
    'max_violations_per_test': 1000,
    'log_level': 'INFO',
}

# =============================================================================
# TEST DEFINITIONS — set interactively via build_config.py
# =============================================================================

NOT_NULL_SINGLE = []

NOT_NULL_COMPOSITE = []

NO_DUPLICATES = []

DATATYPE_CHECKS = []

REQUIRED_ROWS_CONFIG = {
    'enabled':       True,
    'csv_path':      'c:\\Users\\admin\\Documents\\projects\\Test_framework\\required_rows.csv',
    'match_columns': ['trade_id'],
}
